// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1iShHxAGyr7gzubs8DlthuE4-mZGrvGs',
    appId: '1:782204109800:web:08fffa23ab172cb2829a5d',
    messagingSenderId: '782204109800',
    projectId: 'warung-wise',
    authDomain: 'warung-wise.firebaseapp.com',
    storageBucket: 'warung-wise.firebasestorage.app',
    measurementId: 'G-CPLL0F7GXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVRQizgiezqs7esCffoq_nZocGj-VoWvg',
    appId: '1:782204109800:android:569f9df31b45eec1829a5d',
    messagingSenderId: '782204109800',
    projectId: 'warung-wise',
    storageBucket: 'warung-wise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV_kG1PH3u2FcU3YWNpeH9dd3BZoPaGiM',
    appId: '1:782204109800:ios:7e7f768b284ee57f829a5d',
    messagingSenderId: '782204109800',
    projectId: 'warung-wise',
    storageBucket: 'warung-wise.firebasestorage.app',
    iosBundleId: 'com.example.warungWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV_kG1PH3u2FcU3YWNpeH9dd3BZoPaGiM',
    appId: '1:782204109800:ios:7e7f768b284ee57f829a5d',
    messagingSenderId: '782204109800',
    projectId: 'warung-wise',
    storageBucket: 'warung-wise.firebasestorage.app',
    iosBundleId: 'com.example.warungWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1iShHxAGyr7gzubs8DlthuE4-mZGrvGs',
    appId: '1:782204109800:web:cfb8ec90dc41f090829a5d',
    messagingSenderId: '782204109800',
    projectId: 'warung-wise',
    authDomain: 'warung-wise.firebaseapp.com',
    storageBucket: 'warung-wise.firebasestorage.app',
    measurementId: 'G-FFNERED73H',
  );
}
